// src/lib/entities.ts
//
// 「典拠ファイル」：人物・作品・概念の呼び名（表記ゆれ）と、
// 専用記事がある場合はそのslugを登録する場所。
//
// - canonical: 正式な表記（画面に出す時、迷ったらこれを使う）
// - aliases:   検索で拾いたい呼び名のバリエーション（本人＋略称＋別表記など）
// - slug:      この人物・作品を主題にした記事があれば、その記事番号。無ければ null
//
// 使い方：
//   各記事のフロントマターに `subjects: ["fujimoto-yukio", ...]` のように
//   このファイルのキー（entities.ts の一番左の識別子）を書いておくと、
//   テンプレート側でそのIDに対応する aliases が自動的に集められ、
//   画面には見えない検索用テキストとしてページに埋め込まれる。

export const entities = {
 // ── 0001 ──
  "takahashi-yuichi": {
    canonical: "髙橋由一",
    aliases: ["髙橋由一", "高橋由一"], // 「髙」「高」の表記ゆれ
    slug: "0001",
    category: "person", 
  },
  "sake-takahashi": {
    canonical: "鮭（髙橋由一）",
    aliases: ["鮭"],
    slug: "0001",
    category: "work", 
  },
  "tofu-takahashi": {
    canonical: "豆腐（髙橋由一）",
    aliases: ["豆腐"],
    slug: "0001",
    category: "work",  
  },
 "matthew-c-perry": {
    canonical: "マシュー・ペリー",
    aliases: ["ペリー", "マシュー・ペリー", "Matthew C. Perry", "Matthew Calbraith Perry"],
    slug: null,
    category: "person",
  },
  "tai-zu-takahashi": {
    canonical: "鯛図（髙橋由一）",
    aliases: ["鯛図"],
    slug: null,
    category: "work",
  },
  "namaribushi-takahashi": {
    canonical: "なまり節（髙橋由一）",
    aliases: ["なまり節"],
    slug: null,
    category: "work",
  },

  // ── 0002 ──
  "thutmose": {
    canonical: "トトメス",
    aliases: ["トトメス", "Thutmose"],
    slug: "0002",
    category: "person", 
  },
  "nefertiti-bust": {
    canonical: "ネフェルティティの胸像",
    aliases: ["ネフェルティティ", "ネフェルティティの胸像"],
    slug: "0002",
    category: "work", 
  },
    "herodotus": {
    canonical: "ヘロドトス",
    aliases: ["ヘロドトス", "herodotos", "Herodotus", "Herodotos"],
    slug: null,
    category: "person", 
  },
  "napoleon-bonaparte": {
    canonical: "ナポレオン",
    aliases: ["ナポレオン", "ボナパルト", "ナポレオン・ボナパルト", "Napoleon Bonaparte"],
    slug: null,
    category: "person", 
  },
  "adolf-hitler": {
    canonical: "ヒトラー",
    aliases: ["アドルフ・ヒトラー", "アドルフ・ヒットラー",  "Adolf Hitler"],
    slug: null,
    category: "person", 
  },
  "haniwa-dancing-figures": {
    canonical: "埴輪 踊る人々",
    aliases: ["埴輪 踊る人々", "埴輪", "はにわ", "ハニワ"],
    slug: null,
    category: "work",
  },
  "book-of-the-dead-egypt": {
    canonical: "死者の書（古代エジプト）",
    aliases: ["死者の書", "グリーンフィールド・パピルス"],
    slug: null,
    category: "work",
  },
  "herodotus-histories": {
    canonical: "歴史（ヘロドトス）",
    aliases: ["歴史"],
    slug: null,
    category: "work",
  },
  "akhenaten": {
    canonical: "アクエンアテン",
    aliases: ["アクエンアテン", "アメンホテプ4世", "Akhenaten", "Amenhotep IV"],
    slug: null,
    category: "person",
  },
  "nike-of-samothrace": {
    canonical: "サモトラケのニケ",
    aliases: ["サモトラケのニケ"],
    slug: null,
    category: "work",
  },
  "venus-de-milo": {
    canonical: "ミロのヴィーナス",
    aliases: ["ミロのヴィーナス"],
    slug: null,
    category: "work",
  },
  "nazca-lines": {
    canonical: "ナスカの地上絵",
    aliases: ["ナスカの地上絵"],
    slug: null,
    category: "work",
  },
  "moai": {
    canonical: "モアイ",
    aliases: ["モアイ", "イースター島のモアイ"],
    slug: null,
    category: "work",
  },
  "pyramid-battle": {
    canonical: "ピラミッドの戦い",
    aliases: ["ピラミッドの戦い"],
    slug: null,
    category: "concept",
  },

  // ── 0003 ──
  "ishmael-reed": {
    canonical: "イシュメル・リード",
    aliases: ["イシュメル・リード", "Ishmael Reed"],
    slug: "0003",
    category: "person", 
  },
  "mumbo-jumbo": {
    canonical: "マンボ・ジャンボ",
    aliases: ["マンボ・ジャンボ"],
    slug: "0003",
    category: "work", 
  },
  "miles-davis": {
    canonical: "マイルス・デイヴィス",
    aliases: ["マイルス・デイヴィス", "Miles Davis"],
    slug: null,
    category: "person", 
  },
   "wayne-shorter": {
    canonical: "ウェイン・ショーター",
    aliases: ["ウェイン・ショーター", "Wayne Shorter"],
    slug: null,
    category: "person", 
  },
  "nefertiti-album": {
    canonical: "ネフェルティティ（マイルス・デイヴィスのアルバム）",
    aliases: ["ネフェルティティ"],
    slug: null,
    category: "work", 
  },
  "filles-de-kilimanjaro": {
    canonical: "キリマンジャロの娘",
    aliases: ["キリマンジャロの娘"],
    slug: null,
    category: "work", 
  },
  "duke-ellington": {
    canonical: "デューク・エリントン",
    aliases: ["デューク・エリントン", "エリントン", "Duke Ellington"],
    slug: null,
    category: "person", 
 }, 
  "black-and-tan-fantasy": {
    canonical: "黒と茶の幻想",
    aliases: ["黒と茶の幻想", "黒と褐色の幻想"],
    slug: null,
    category: "work", 
  },
  "thoth": {
    canonical: "トト",
    aliases: ["トト", "トート", "トト神", "トート神", "Thoth"],
    slug: null,
    category: "person", 
  },
  "bud-powell": {
    canonical: "バド・パウエル",
    aliases: ["バド・パウエル", "Bud Powell"],
    slug: null,
    category: "person",
  },
  "cleopatras-dream": {
    canonical: "クレオパトラの夢",
    aliases: ["クレオパトラの夢"],
    slug: null,
    category: "work",
  },
 "harlem-renaissance": {
    canonical: "ハーレム・ルネサンス",
    aliases: ["ハーレム・ルネサンス"],
    slug: null,
    category: "concept",
  },
 "afrocentrism": {
    canonical: "アフロセントリズム",
    aliases: ["アフロセントリズム", "アフリカ中心主義"],
    slug: null,
    category: "concept",
  },
 "black-arts-movement": {
    canonical: "ブラック・アーツ・ムーブメント",
    aliases: ["ブラック・アーツ・ムーブメント", "黒人芸術運動"],
    slug: null,
    category: "concept",
 },
"jes-grew": {
    canonical: "ジェス・グルー",
    aliases: ["ジェス・グルー", "ジェスラ", "Jes Grew"],
    slug: null,
    category: "concept",
  },

// ── 0004 ──
  "caetano-veloso": {
    canonical: "カエターノ・ヴェローゾ",
    aliases: ["カエターノ・ヴェローゾ", "カエターノ", "Caetano Veloso"],
    slug: "0004",
    category: "person", 
  },
  "araca-azul": {
    canonical: "アラサー・アズール",
    aliases: ["アラサー・アズール"],
    slug: "0004",
    category: "work", 
  },
  "fidel-castro": {
    canonical: "フィデル・カストロ",
    aliases: ["カストロ", "Fidel Castro"],
    slug: null,
    category: "person", 
  },
  "che-guevara": {
    canonical: "チェ・ゲバラ",
    aliases: ["ゲバラ", "Che Guevara", "Ernesto Guevara"],
    slug: null,
    category: "person", 
  },
  "castelo-branco": {
    canonical: "カステロ・ブランコ",
    aliases: ["ブランコ", "Castelo Branco"],
    slug: null,
    category: "person", 
  },
  "gilberto-gil": {
    canonical: "ジルベルト・ジル",
    aliases: ["ジルベルト・ジル", "Gilberto Gil"],
    slug: null,
    category: "person", 
  },
  "gal-costa": {
    canonical: "ガル・コスタ",
    aliases: ["ガル・コスタ", "Gal Costa"],
    slug: null,
    category: "person", 
  },
  "os-mutantes": {
    canonical: "ムタンチス",
    aliases: ["ムタンチス", "Os Mutantes"],
    slug: null,
    category: "person", 
  },
    "kurt-cobain": {
    canonical: "カート・コバーン",
    aliases: ["カート・コバーン", "Kurt Cobain"],
    slug: null,
    category: "person", 
  },
  "beck-musician": {
    canonical: "ベック",
    aliases: ["ベック", "Beck", "Beck Hansen"],
    slug: null,
    category: "person", 
  },
  "david-byrne": {
    canonical: "デイヴィッド・バーン",
    aliases: ["デイヴィッド・バーン", "David Byrne"],
    slug: null,
    category: "person", 
  },
  "tom-ze": {
    canonical: "トン・ゼー",
    aliases: ["トン・ゼー", "Tom Zé"],
    category: "person", 
    slug: null,
  },
  "todos-os-olhos": {
    canonical: "Todos os Olhos",
    aliases: ["すべての目", "todos os olhos", "Todos Os Olhos"],
    category: "work", 
    slug: null,
  },
  "helio-oiticica": {
    canonical: "エリオ・オイティシカ",
    aliases: ["エリオ・オイティシカ", "Hélio Oiticica"],
    category: "person", 
    slug: null,
  },
  "tropicalia": {
    canonical: "トロピカリア",
    aliases: ["トロピカリア", "Tropicália"],
    category: "work", 
    slug: null,
  },
  "lygia-clark": {
    canonical: "リジア・クラーク",
    aliases: ["リジア・クラーク", "Lygia Clark"],
    category: "person", 
    slug: null,
  },
  "glauber-rocha": {
    canonical: "グラウベル・ローシャ",
    aliases: ["グラウベル・ローシャ", "Glauber Rocha"],
    category: "person", 
    slug: null,
  },
  "entranced-earth": {
    canonical: "狂乱の大地",
    aliases: ["Terra em Transe", "Entranced Earth"],
    category: "work", 
    slug: null,
  },
  "antonio-das-mortes": {
    canonical: "アントニオ・ダス・モルテス",
    aliases: ["Antonio das Mortes", "O Dragão da Maldade contra o Santo Guerreiro"],
    category: "work", 
    slug: null,
  },
  "joaquim-pedro-de-Andrade": {
    canonical: "ジョアキン・ペドロ・デ・アンドラーデ",
    aliases: ["ペドロ・デ・アンドラーデ", "ジョアキン・ペドロ・デ・アンドラーデ", "Joaquim Pedro de Andrade"],
    category: "person", 
    slug: null,
  },
  "mario-de-andrade": {
    canonical: "マリオ・デ・アンドラーデ",
    aliases: ["マリオ・デ・アンドラーデ", "Mário de Andrade"],
    category: "person", 
    slug: null,
  },
  "macunaima-cinema": {
    canonical: "マクナイーマ（映画）",
    aliases: ["マクナイーマ", "Macunaíma"],
    category: "work", 
    slug: null,
  },
  "macunaima-novel": {
    canonical: "マクナイーマ（小説）",
    aliases: ["マクナイーマ", "Macunaíma"],
    category: "work", 
    slug: null,
  },
  "jose-celso-martinez-correa": {
    canonical: "ジョゼ・セルソ・マルチネス・コレア",
    aliases: ["ジョゼ・セルソ・マルチネス・コレア", "José Celso Martinez Corrêa"],
    category: "person", 
    slug: null,
  },
  "o-rei-da-vela": {
    canonical: "オ・レイ・ダ・ヴェラ",
    aliases: ["オ・レイ・ダ・ヴェラ", "金貸し王", "O Rei da Vela"],
    category: "work", 
    slug: null,
  },
  "tarsila-do-amaral": {
    canonical: "タルシラ・ド・アマラル",
    aliases: ["タルシラ・ド・アマラル", "Tarsila do Amaral"],
    slug: null,
    category: "person", 
  },
  "abaporu": {
    canonical: "アバポル",
    aliases: ["アバポル", "Abaporu"],
    category: "work", 
    slug: null,
  },
  "rogerio-duprat": {
    canonical: "ホジェリオ・ドゥプラ",
    aliases: ["ホジェリオ・ドゥプラ", "Rogério Duprat"],
    slug: null,
    category: "person", 
  },
  "karlheinz-stockhausen": {
    canonical: "カールハインツ・シュトックハウゼン",
    aliases: [ "カールハインツ・シュトックハウゼン", "Karlheinz Stockhausen"],
    slug: null,
    category: "person", 
  },
  "pierre-boulez": {
    canonical: "ピエール・ブーレーズ",
    aliases: ["ピエール・ブーレーズ",  "Pierre Boulez"],
    slug: null,
    category: "person", 
  },
  "luciano-berio": {
    canonical: "ルチアーノ・ベリオ",
    aliases: ["ルチアーノ・ベリオ", "Luciano Berio"],
    slug: null,
    category: "person", 
  },
  "sinfonia": {
    canonical: "シンフォニア（ルチアーノ・ベリオ）",
    aliases: ["シンフォニア", "Sinfonia"],
    slug: null,
   category: "work", 
  },
  "cathy-berberian": {
    canonical: "キャシー・バーベリアン",
    aliases: ["キャシー・バーベリアン", "Cathy Berberian"],
    slug: null,
    category: "person", 
  },
  "stripsody ": {
    canonical: "ストリプソディ",
    aliases: ["ストリプソディ", "Stripsody "],
    slug: null,
    category: "work", 
  },
  "haroldo-de-campos": {
    canonical: "アロウド・ジ・カンポス",
    aliases: ["アロウド・ジ・カンポス", "Haroldo de Campos"],
    slug: null,
    category: "person", 
  },
  "miura-jun": {
    canonical: "みうらじゅん",
    aliases: ["みうらじゅん", "Miura Jun"],
    slug: null,
    category: "person", 
  },
  "cuban-revolution": {
    canonical: "キューバ革命",
    aliases: ["キューバ革命"],
    slug: null,
    category: "concept",
  },
  "tropicalismo": {
    canonical: "トロピカリスモ",
    aliases: ["トロピカリスモ", "トロピカリア", "Tropicália", "Tropicalismo"],
    slug: null,
    category: "concept",
  },
  "oswald-de-andrade": {
    canonical: "オズヴァルド・ジ・アンドラーデ",
    aliases: ["オズヴァルド・ジ・アンドラーデ", "オズヴァルド・デ・アンドラーデ", "Oswald de Andrade"],
    slug: null,
    category: "person",
  },
  "manifesto-antropofago": {
    canonical: "食人宣言",
    aliases: ["食人宣言", "マニフェスト・アントロポファジア", "Manifesto Antropófago"],
    slug: null,
    category: "work",
  },
  "anthropophagy": {
    canonical: "アントロポファジア",
    aliases: ["アントロポファジア", "食人運動", "Antropofagia"],
    slug: null,
    category: "concept",
  },
  "cinema-novo": {
    canonical: "シネマ・ノーヴォ",
    aliases: ["シネマ・ノーヴォ", "Cinema Novo"],
    slug: null,
    category: "concept",
  },
  "julia-moreno": {
    canonical: "Júlia/Moreno",
    aliases: ["Júlia/Moreno"],
    slug: null,
    category: "work",
  },
  "tu-me-acostumbraste": {
    canonical: "Tu Me Acostumbraste",
    aliases: ["Tu Me Acostumbraste"],
    slug: null,
    category: "work",
  },
  "de-palavra-em-palavra": {
    canonical: "De Palavra em Palavra",
    aliases: ["De Palavra em Palavra"],
    slug: null,
    category: "work",
  },
  "concrete-poetry": {
    canonical: "具体詩",
    aliases: ["具体詩", "コンクリート・ポエトリー", "Poesia Concreta"],
    slug: null,
    category: "concept",
  },

  // ── 0005 ──
  "villa-lobos": {
    canonical: "エイトール・ヴィラ＝ロボス",
    aliases: ["エイトール・ヴィラ＝ロボス", "ヴィラ＝ロボス", "ヴィラ゠ロボス", "Villa-Lobos"],
    slug: "0005",
    category: "person", 
  },
   "bachianas-brasileiras-1": {
    canonical: "ブラジル風バッハ第1番",
    aliases: ["ブラジル風バッハ第1番", "ブラジル風バッハ"],
    slug: "0005",
    category: "work", 
  },
   "bachianas-brasileiras-5": {
    canonical: "ブラジル風バッハ第5番",
    aliases: ["ブラジル風バッハ第5番", "ブラジル風バッハ"],
    slug: null,
    category: "work", 
  },
  "lalo-schifrin": {
    canonical: "ラロ・シフリン",
    aliases: ["ラロ・シフリン", "Lalo Schifrin"],
    slug: null,
    category: "person", 
  },
  "new-fantasy-schifrin": {
   canonical: "New Fantasy（ラロ・シフリン）",
   aliases: ["New Fantasy"],
   slug: null,
   category: "work",
  },

// ── 0006 ──
  "daniel-schmid": {
    canonical: "ダニエル・シュミット",
    aliases: ["ダニエル・シュミット", "Daniel Schmid"],
    slug: "0006",
    category: "person", 
  },
  "la-paloma-film": {
    canonical: "ラ・パロマ（映画）",
    aliases: ["ラ・パロマ"],
    slug: "0006",
    category: "work", 
  },
  "sebastian-iradier": {
    canonical: "セバスティアン・イラディエル",
    aliases: ["セバスティアン・イラディエル", "Sebastián Iradier"],
    slug: null,
    category: "person", 
  },
  "la-paloma-music": {
    canonical: "ラ・パロマ（音楽）",
    aliases: ["ラ・パロマ"],
    slug: "0006",
    category: "work", 
  },
  "georges-bizet": {
    canonical: "ジョルジュ・ビゼー",
    aliases: ["ジョルジュ・ビゼー", "Georges Bizet"],
    slug: null,
    category: "person", 
  },
  "carmen": {
    canonical: "カルメン",
    aliases: ["カルメン", "Carmen"],
    slug: null, // 単独記事の予定あり
    category: "work", 
  },
  "nakamura-toyo": {
    canonical: "中村とうよう",
    aliases: ["中村とうよう"],
    slug: null, // 単独記事の予定あり
    category: "person", 
  },
  "john-philip-sousa": {
    canonical: "ジョン・フィリップ・スーザ",
    aliases: ["スーザ", "ジョン・フィリップ・スーザ","John Philip Sousa"],
    slug: null,
    category: "person", 
  },
 "eva-peron": {
    canonical: "エヴァ・ペロン",
    aliases: ["エヴィータ", "エビータ", "エヴァ・ペロン", "エバ・ペロン"," Eva Perón", "Evita"],
    slug: null,
    category: "person", 
  },
 "erich-wolfgang-korngold": {
    canonical: "エーリヒ・ヴォルフガング・コルンゴルト",
    aliases: ["コルンゴルト", "ヴォルフガング・コルンゴルト", "エーリヒ・ヴォルフガング・コルンゴルト", "Erich Wolfgang Korngold"],
    slug: null,
    category: "person", 
  },
 "die-tote-stadt": {
    canonical: "死の都",
    aliases: ["死の都", "Die tote Stadt"],
    slug: null,
    category: "work", 
  },
 "giuseppe-verdi": {
    canonical: "ジュゼッペ・ヴェルディ",
    aliases: ["ジュゼッペ・ヴェルディ", "Giuseppe Verdi"],
    slug: null,
    category: "person", 
  },
 "la-traviata": {
    canonical: "椿姫",
    aliases: ["椿姫", "La traviata"],
    slug: null,
    category: "work", 
  },
 "gaetano-donizett": {
    canonical: "ガエターノ・ドニゼッティ",
    aliases: ["ガエターノ・ドニゼッティ", "Gaetano Donizetti"],
    slug: null,
    category: "person", 
  },
 "lucia-di-lammermoor": {
    canonical: "ランメルモールのルチア",
    aliases: ["ランメルモールのルチア", "Lucia di Lammermoor"],
    slug: null,
    category: "work", 
  },
 "vincenzo-bellini": {
    canonical: "ヴィンチェンツォ・ベッリーニ",
    aliases: ["ヴィンチェンツォ・ベッリーニ", "Vincenzo Bellini"],
    slug: null,
    category: "person", 
  },
 "a-sonnambula": {
    canonical: "夢遊病の女",
    aliases: ["夢遊病の女", "a Sonnambula"],
    slug: null,
    category: "work", 
  },
 "rainer-werner-fassbinder": {
    canonical: "ライナー・ヴェルナー・ファスビンダー",
    aliases: ["ファスビンダー", "ライナー・ヴェルナー・ファスビンダー", "Rainer Werner Fassbinder"],
    slug: null,
    category: "person", 
  },
 "ingrid-caven": {
    canonical: "イングリット・カーフェン",
    aliases: ["イングリット・カーフェン", "Ingrid Caven"],
    slug: null,
    category: "person", 
  },
  "ohno-kazuo": {
    canonical: "大野一雄",
    aliases: ["大野一雄", "Ono Kazuo"],
    slug: null, // 単独記事の予定あり
    category: "person", 
  },
  "richard-tauber": {
  canonical: "リヒャルト・タウバー",
  aliases: ["リヒャルト・タウバー", "Richard Tauber"],
  slug: null,
  category: "person",
  },
 "mariettas-lied": {
  canonical: "私に残された幸せ（マリエッタの唄）",
  aliases: ["私に残された幸せ", "マリエッタの唄", "Mariettas Lied"],
  slug: null,
  category: "work",
  },
 "massenet-manon": {
  canonical: "マノン（マスネー）",
  aliases: ["マノン"],
  slug: null,
  category: "work",
  },
 "tango-film-company": {
  canonical: "タンゴ・フィルム",
  aliases: ["タンゴ・フィルム"],
  slug: null,
  category: "work",
  },
 "ohno-la-argentina": {
  canonical: "ラ・アルヘンティーナを讃えて",
  aliases: ["ラ・アルヘンティーナを讃えて", "アルゼンチンを讃えて"],
  slug: null,
  category: "work",
 },
 "written-face": {
  canonical: "書かれた顔",
  aliases: ["書かれた顔"],
  slug: null,
  category: "work",
  },
 "habanera": {
  canonical: "ハバネラ",
  aliases: ["ハバネラ", "恋は野の鳥"],
  slug: null,
  category: "concept",
  },

  // ── 0007 ──
 "stefan-zweig": {
    canonical: "シュテファン・ツヴァイク",
    aliases: ["シュテファン・ツヴァイク", "ツヴァイク", "Stefan Zweig"],
    slug: "0007",
    category: "person", 
  },
 "the-world-of-yesterday": {
    canonical: "昨日の世界",
    aliases: ["昨日の世界"],
    slug: "0007",
    category: "work", 
  },
 "teatro-colon": {
  canonical: "テアトル・コロン",
  aliases: ["テアトル・コロン", "コロン劇場", "Teatro Colón"],
  slug: null,
  category: "work",
  },
 "chess-story-zweig": {
  canonical: "チェスの話（ツヴァイク）",
  aliases: ["チェスの話", "チェス奇譚", "Schachnovelle"],
  slug: null,
  category: "work",
  },
 "brazil-land-of-future": {
  canonical: "未来の国ブラジル（ツヴァイク）",
  aliases: ["未来の国ブラジル"],
  slug: null,
  category: "work",
  },
 "erich-kleiber": {
  canonical: "エーリッヒ・クライバー",
  aliases: ["エーリッヒ・クライバー", "Erich Kleiber"],
  slug: null,
  category: "person",
  },
 "fritz-busch": {
  canonical: "フリッツ・ブッシュ",
  aliases: ["フリッツ・ブッシュ", "Fritz Busch"],
  slug: null,
  category: "person",
  },
 "getulio-vargas": {
  canonical: "ジェトゥリオ・ヴァルガス",
  aliases: ["ジェトゥリオ・ヴァルガス", "ヴァルガス", "Getúlio Vargas"],
  slug: null,
  category: "person",
  },
 "adolf-eichmann": {
  canonical: "アドルフ・アイヒマン",
  aliases: ["アドルフ・アイヒマン", "アイヒマン", "Adolf Eichmann"],
  slug: null,
  category: "person",
  },
 "josef-mengele": {
  canonical: "ヨーゼフ・メンゲレ",
  aliases: ["ヨーゼフ・メンゲレ", "メンゲレ", "Josef Mengele"],
  slug: null,
  category: "person",
  },
 "das-andere-deutschland": {
  canonical: "もうひとつのドイツ",
  aliases: ["もうひとつのドイツ", "Das andere Deutschland"],
  slug: null,
  category: "concept",
  },

  // ── 0008 ──
 "maurice-ravel": {
  canonical: "モリス・ラヴェル",
  aliases: ["モリス・ラヴェル", "ラヴェル", "ラベル", "Ravel"],
  slug: "0008",
  category: "person",
  },
 "la-valse": {
  canonical: "ラ・ヴァルス",
  aliases: ["ラ・ヴァルス", "La Valse"],
  slug: "0008",
  category: "work",
  },
 "bolero": {
  canonical: "ボレロ",
  aliases: ["ボレロ", "Boléro"],
  slug: null,
   category: "work",
  },
 "red-vienna": {
  canonical: "赤いウィーン",
  aliases: ["赤いウィーン"],
  slug: null,
  category: "concept",
  },
 "karl-marx-hof": {
  canonical: "カール・マルクス・ホーフ",
  aliases: ["カール・マルクス・ホーフ", "Karl-Marx-Hof"],
  slug: null,
  category: "work",
  },
 "pavane-pour-une-infante": {
  canonical: "死せる王女のためのパヴァーヌ",
  aliases: ["死せる王女のためのパヴァーヌ", "亡き王女のためのパヴァーヌ"],
  slug: null,
  category: "work",
},
"menuet-antique": {
  canonical: "古風なメヌエット",
  aliases: ["古風なメヌエット"],
  slug: null,
  category: "work",
},
"piano-trio-ravel": {
  canonical: "ピアノ三重奏曲（ラヴェル）",
  aliases: ["ピアノ三重奏曲"],
  slug: null,
  category: "work",
},
"tombeau-de-couperin": {
  canonical: "クープランの墓",
  aliases: ["クープランの墓", "Le Tombeau de Couperin"],
  slug: null,
  category: "work",
},
"daphnis-et-chloe": {
  canonical: "ダフニスとクロエ",
  aliases: ["ダフニスとクロエ", "Daphnis et Chloé"],
  slug: null,
  category: "work",
},
"string-quartet-ravel": {
  canonical: "弦楽四重奏曲（ラヴェル）",
  aliases: ["弦楽四重奏曲"],
  slug: null,
  category: "work",
},
"sonata-violin-cello-ravel": {
  canonical: "ヴァイオリンとチェロのためのソナタ（ラヴェル）",
  aliases: ["ヴァイオリンとチェロのためのソナタ"],
  slug: null,
  category: "work",
},
"lenfant-et-les-sortileges": {
  canonical: "子供と魔法",
  aliases: ["子供と魔法", "子どもと魔法", "L'enfant et les sortilèges"],
  slug: null,
  category: "work",
},
"left-hand-concerto": {
  canonical: "左手のためのピアノ協奏曲",
  aliases: ["左手のためのピアノ協奏曲"],
  slug: null,
  category: "work",
},
"piano-concerto-g-ravel": {
  canonical: "ピアノ協奏曲ト長調（ラヴェル）",
  aliases: ["ピアノ協奏曲ト長調"],
  slug: null,
  category: "work",
},
"pictures-at-an-exhibition": {
  canonical: "展覧会の絵",
  aliases: ["展覧会の絵"],
  slug: null,
  category: "work",
},
"johann-strauss-ii": {
  canonical: "ヨハン・シュトラウス2世",
  aliases: ["ヨハン・シュトラウス二世", "ヨハン・シュトラウス2世", "Johann Strauss II"],
  slug: null,
  category: "person",
},
"franz-joseph-i": {
  canonical: "フランツ・ヨーゼフ1世",
  aliases: ["フランツ・ヨーゼフ1世", "Franz Joseph I"],
  slug: null,
  category: "person",
},
"empress-elisabeth": {
  canonical: "エリザベート（シシィ）",
  aliases: ["エリザベート", "シシィ", "Elisabeth"],
  slug: null,
  category: "person",
},
"richard-strauss": {
  canonical: "リヒャルト・シュトラウス",
  aliases: ["リヒャルト・シュトラウス", "Richard Strauss"],
  slug: null,
  category: "person",
},
"sakamoto-ryuichi": {
  canonical: "坂本龍一",
  aliases: ["坂本龍一"],
  slug: null,
  category: "person",
},
"nishimura-akira": {
  canonical: "西村朗",
  aliases: ["西村朗"],
  slug: null,
  category: "person",
},
"depouillement": {
  canonical: "デプイユマン",
  aliases: ["デプイユマン", "dépouillement"],
  slug: null,
  category: "concept",
},
"illusory-instrument": {
  canonical: "幻影の楽器",
  aliases: ["幻影の楽器", "Illusory Instrument"],
  slug: null,
  category: "concept",
},

  // ── 0009 ──
  "alberto-giacometti": {
    canonical: "アルベルト・ジャコメッティ",
    aliases: ["アルベルト・ジャコメッティ", "ジャコメッティ", "Giacometti"],
    slug: "0009",
    category: "person",
  },
  "palace-at-4am": {
    canonical: "午前四時の宮殿",
    aliases: ["午前四時の宮殿"],
    slug: "0009",
    category: "work",
  },
  "fujimoto-yukio": {
    canonical: "藤本由紀夫",
    aliases: ["藤本由紀夫"],
    slug: null,
    category: "person",
  },
  "marcel-duchamp": {
    canonical: "マルセル・デュシャン",
    aliases: ["マルセル・デュシャン", "デュシャン", "Marcel Duchamp"],
    slug: null, // 単独記事の予定あり
    category: "person",
  },
  "inagaki-taruho": {
    canonical: "稲垣足穂",
    aliases: ["稲垣足穂", "タルホ"],
    slug: null, // 単独記事の予定あり
    category: "person",
  },
  "louis-sullivan": {
  canonical: "ルイス・サリヴァン",
  aliases: ["ルイス・サリヴァン", "Louis Sullivan"],
  slug: null,
  category: "person",
},
"mies-van-der-rohe": {
  canonical: "ミース・ファン・デル・ローエ",
  aliases: ["ミース・ファン・デル・ローエ", "ミース", "Mies van der Rohe"],
  slug: null,
  category: "person",
},
"arnold-schoenberg": {
  canonical: "アルノルト・シェーンベルク",
  aliases: ["アルノルト・シェーンベルク", "シェーンベルク", "Arnold Schoenberg"],
  slug: null,
  category: "person",
},
"anton-webern": {
  canonical: "アントン・ヴェーベルン",
  aliases: ["アントン・ヴェーベルン", "ヴェーベルン", "Anton Webern"],
  slug: null,
  category: "person",
},
"webern-bagatelles": {
  canonical: "弦楽四重奏のための6つのバガテル Op.9（ヴェーベルン）",
  aliases: ["弦楽四重奏のための6つのバガテル", "6つのバガテル"],
  slug: null,
  category: "work",
},
"jorge-luis-borges": {
  canonical: "ホルヘ・ルイス・ボルヘス",
  aliases: ["ホルヘ・ルイス・ボルヘス", "ボルヘス", "Jorge Luis Borges"],
  slug: null,
  category: "person",
},
"borges-ficciones": {
  canonical: "伝記集（ボルヘス）",
  aliases: ["伝記集"],
  slug: null,
  category: "work",
},
"inframince": {
  canonical: "アンフラマンス",
  aliases: ["アンフラマンス", "inframince", "超薄", "極薄"],
  slug: null,
  category: "concept",
},
"taruho-thin-world": {
  canonical: "薄板界（稲垣足穂）",
  aliases: ["薄板界"],
  slug: null,
  category: "concept",
},
"taruho-to-kokuu": {
  canonical: "タルホと虚空",
  aliases: ["タルホと虚空"],
  slug: null,
  category: "work",
},
"usui-machi": {
  canonical: "薄い街（稲垣足穂）",
  aliases: ["薄い街"],
  slug: null,
  category: "work",
},
"fujimoto-stars": {
  canonical: "STARS（藤本由紀夫）",
  aliases: ["STARS"],
  slug: null,
  category: "work",
},
"ikeda-kikunae": {
  canonical: "池田菊苗",
  aliases: ["池田菊苗"],
  slug: null,
  category: "person",
},
"form-follows-function": {
  canonical: "形態は機能に従う",
  aliases: ["形態は機能に従う", "Form follows function"],
  slug: null,
  category: "concept",
},
"less-is-more": {
  canonical: "Less is More",
  aliases: ["Less is More"],
  slug: null,
  category: "concept",
},

  // ── 0010 ──
"cycladic-civilization": {
  canonical: "キクラデス文明",
  aliases: ["キクラデス文明", "キクラデス"],
  slug: "0010",
  category: "concept",  // work → concept
},
"cycladic-female-figure": {
  canonical: "キクラデスの女性像",
  aliases: ["キクラデスの女性像"],
  slug: null,
  category: "work",
},
"christos-tsountas": {
  canonical: "クリストス・ツンタス",
  aliases: ["クリストス・ツンタス", "Christos Tsountas"],
  slug: null,
  category: "person",
},
"heinrich-schliemann": {
  canonical: "シュリーマン",
  aliases: ["シュリーマン", "Heinrich Schliemann"],
  slug: null,
  category: "person",
},
"arthur-evans": {
  canonical: "エヴァンズ",
  aliases: ["エヴァンズ", "Arthur Evans"],
  slug: null,
  category: "person",
},
"minoan-civilization": {
  canonical: "ミノア文明",
  aliases: ["ミノア文明", "クレタ文明"],
  slug: null,
  category: "concept",
},
"mycenaean-civilization": {
  canonical: "ミケーネ文明",
  aliases: ["ミケーネ文明"],
  slug: null,
  category: "concept",
},
"brancusi-pogany": {
  canonical: "ポガニー嬢の肖像（ブランクーシ）",
  aliases: ["ポガニー嬢の肖像"],
  slug: null,
  category: "work",
},
  "cycladic-frying-pan": {
    canonical: "キクラデスのフライパン",
    aliases: ["キクラデスのフライパン"],
    slug: "0010",
    category: "work",
  },
  "constantin-brancusi": {
    canonical: "コンスタンティン・ブランクーシ",
    aliases: ["コンスタンティン・ブランクーシ", "ブランクーシ", "Brâncuși"],
    slug: null,
    category: "person",
  },
  "hans-coper": {
    canonical: "ハンス・コパー",
    aliases: ["ハンス・コパー", "Hans Coper"],
    slug: null,
    category: "person",
  },

  // ── 0011（デヴィッド・マンロウ）──
  "david-munrow": {
    canonical: "デヴィッド・マンロウ",
    aliases: ["デヴィッド・マンロウ", "マンロウ", "David Munrow"],
    slug: "0011",
    category: "person",
  },
  "pentangle": {
    canonical: "ペンタングル",
    aliases: ["ペンタングル", "Pentangle"],
    slug: null,
    category: "person",
  },
  "fairport-convention": {
    canonical: "フェアポート・コンヴェンション",
    aliases: ["フェアポート・コンヴェンション", "Fairport Convention"],
    slug: null,
    category: "person",
  },
  "steeleye-span": {
    canonical: "スティーライ・スパン",
    aliases: ["スティーライ・スパン", "Steeleye Span"],
    slug: null,
    category: "person",
  },
  "yoshida-hidekazu": {
    canonical: "吉田秀和",
    aliases: ["吉田秀和"],
    slug: null,
    category: "person",
  },
  "villiers-de-lisle-adam": {
  canonical: "ヴィリエ・ド・リラダン",
  aliases: ["ヴィリエ・ド・リラダン", "Villiers de l'Isle-Adam"],
  slug: null,
  category: "person",
},
"future-eve": {
  canonical: "未来のイヴ",
  aliases: ["未来のイヴ"],
  slug: null,
  category: "work",
},
"thomas-edison": {
  canonical: "エジソン",
  aliases: ["エジソン", "Thomas Edison"],
  slug: null,
  category: "person",
},
"olin-downes": {
  canonical: "オーリン・ダウンズ",
  aliases: ["オーリン・ダウンズ", "Olin Downes"],
  slug: null,
  category: "person",
},
"instruments-medieval-renaissance": {
  canonical: "中世・ルネサンスの楽器",
  aliases: ["中世・ルネサンスの楽器"],
  slug: "0011",
  category: "work",
},
"gryphon-band": {
  canonical: "グリフォン",
  aliases: ["グリフォン", "Gryphon"],
  slug: null,
  category: "person",
},
"paul-mccartney": {
  canonical: "ポール・マッカートニー",
  aliases: ["ポール・マッカートニー", "Paul McCartney"],
  slug: null,
  category: "person",
},
"jimi-hendrix": {
  canonical: "ジミ・ヘンドリックス",
  aliases: ["ジミ・ヘンドリックス", "Jimi Hendrix"],
  slug: null,
  category: "person",
},
"carole-king": {
  canonical: "キャロル・キング",
  aliases: ["キャロル・キング", "Carole King"],
  slug: null,
  category: "person",
},
"brian-wilson": {
  canonical: "ブライアン・ウィルソン",
  aliases: ["ブライアン・ウィルソン", "Brian Wilson"],
  slug: null,
  category: "person",
},
"aretha-franklin": {
  canonical: "アレサ・フランクリン",
  aliases: ["アレサ・フランクリン", "Aretha Franklin"],
  slug: null,
  category: "person",
},
"led-zeppelin": {
  canonical: "レッド・ツェッペリン",
  aliases: ["レッド・ツェッペリン", "Led Zeppelin"],
  slug: null,
  category: "person",
},
"stairway-to-heaven": {
  canonical: "天国への階段",
  aliases: ["天国への階段", "Stairway to Heaven"],
  slug: null,
  category: "work",
},
"battle-of-evermore": {
  canonical: "限りなき戦い",
  aliases: ["限りなき戦い", "The Battle of Evermore"],
  slug: null,
  category: "work",
},
"jimmy-page": {
  canonical: "ジミー・ペイジ",
  aliases: ["ジミー・ペイジ", "Jimmy Page"],
  slug: null,
  category: "person",
},
"robert-plant": {
  canonical: "ロバート・プラント",
  aliases: ["ロバート・プラント", "Robert Plant"],
  slug: null,
  category: "person",
},
"bert-jansch": {
  canonical: "バート・ヤンシュ",
  aliases: ["バート・ヤンシュ", "Bert Jansch"],
  slug: null,
  category: "person",
},
"roy-harper": {
  canonical: "ロイ・ハーパー",
  aliases: ["ロイ・ハーパー", "Roy Harper"],
  slug: null,
  category: "person",
},
"glenn-gould": {
  canonical: "グレン・グールド",
  aliases: ["グレン・グールド", "Glenn Gould"],
  slug: null,
  category: "person",
},
"shirley-collins": {
  canonical: "シャーリー・コリンズ",
  aliases: ["シャーリー・コリンズ", "Shirley Collins"],
  slug: null,
  category: "person",
},
"anthems-in-eden": {
  canonical: "Anthems in Eden",
  aliases: ["Anthems in Eden"],
  slug: null,
  category: "work",
},
"abbey-road-studios": {
  canonical: "アビイ・ロード・スタジオ",
  aliases: ["アビイ・ロード・スタジオ", "Abbey Road Studios"],
  slug: null,
  category: "work",
},
"swinging-london": {
  canonical: "スウィンギン・ロンドン",
  aliases: ["スウィンギン・ロンドン", "Swinging London"],
  slug: null,
  category: "concept",
},
"british-folk-revival": {
  canonical: "ブリティッシュ・フォーク・リヴァイヴァル",
  aliases: ["ブリティッシュ・フォーク・リヴァイヴァル", "ブリティッシュ・フォーク・リバイバル"],
  slug: null,
  category: "concept",
},

  // ── 0012（折口信夫）──
  // 「死者の書」は0002（古代エジプトの文書）と同名なので、別エントリとして分離。
  "orikuchi-shinobu": {
    canonical: "折口信夫",
    aliases: ["折口信夫"],
    slug: "0012",
    category: "person",
  },
  "shisha-no-sho-orikuchi": {
    canonical: "死者の書（折口信夫）",
    aliases: ["死者の書"],
    slug: "0012",
    category: "work",
  },
    "otsu-no-miko": {
    canonical: "大津皇子",
    aliases: ["大津皇子"],
    slug: "null",
    category: "person",
  },
  "nakazawa-shinichi": {
    canonical: "中沢新一",
    aliases: ["中沢新一"],
    slug: "null",
    category: "person",
  },
  "yoshimoto-takaaki": {
    canonical: "吉本隆明",
    aliases: ["吉本隆明"],
    slug: "null",
    category: "person",
  },
    "kobayashi-hideo": {
    canonical: "小林秀雄",
    aliases: ["小林秀雄"],
    slug: "null",
    category: "person",
  },
    "hasumi-shigehiko": {
    canonical: "蓮實重彦",
    aliases: ["蓮實重彦"],
    slug: "null",
    category: "person",
  },
    "kawamoto-kihachiro": {
    canonical: "川本喜八郎",
    aliases: ["川本喜八郎"],
    slug: "null",
    category: "person",
  },
  "hashihaka-kofun": {
  canonical: "箸墓古墳",
  aliases: ["箸墓古墳", "箸墓"],
  slug: null,
  category: "work",
},
"himiko": {
  canonical: "卑弥呼",
  aliases: ["卑弥呼"],
  slug: null,
  category: "person",
},
"yamatototohimomosohime": {
  canonical: "倭迹迹日百襲姫",
  aliases: ["倭迹迹日百襲姫", "やまとととひももそひめのみこと"],
  slug: null,
  category: "person",
},
"kasai-shinya": {
  canonical: "笠井新也",
  aliases: ["笠井新也"],
  slug: null,
  category: "person",
},
"toritaniguchi-kofun": {
  canonical: "鳥谷口古墳",
  aliases: ["鳥谷口古墳"],
  slug: null,
  category: "work",
},
"ooku-no-himemiko": {
  canonical: "大伯皇女",
  aliases: ["大伯皇女", "おおくのひめみこ"],
  slug: null,
  category: "person",
},
"mount-nijo": {
  canonical: "二上山",
  aliases: ["二上山", "ふたかみやま"],
  slug: null,
  category: "work",
},
"manyoshu": {
  canonical: "万葉集",
  aliases: ["万葉集"],
  slug: null,
  category: "work",
},
"marebito": {
  canonical: "まれびと",
  aliases: ["まれびと", "客人"],
  slug: null,
  category: "concept",
},
"tamafuri": {
  canonical: "たまふり",
  aliases: ["たまふり", "魂振り"],
  slug: null,
  category: "concept",
},
"daijosai-no-hongi": {
  canonical: "大嘗祭の本義（折口信夫）",
  aliases: ["大嘗祭の本義"],
  slug: null,
  category: "work",
},
"ruikaseino": {
  canonical: "類化性能",
  aliases: ["類化性能"],
  slug: null,
  category: "concept",
},
"bekkaseino": {
  canonical: "別化性能",
  aliases: ["別化性能"],
  slug: null,
  category: "concept",
},
"ito-hiroshi-manyogaku": {
  canonical: "伊藤博",
  aliases: ["伊藤博"],
  slug: null,
  category: "person",
},
"shigajitsuhiko": {
  canonical: "滋賀津彦",
  aliases: ["滋賀津彦"],
  slug: null,
  category: "person",
},
"mimimotoji": {
  canonical: "耳面刀自",
  aliases: ["耳面刀自", "みみのもとじ"],
  slug: null,
  category: "person",
},
"fujiwara-toyonari": {
  canonical: "藤原南家豊成",
  aliases: ["藤原南家豊成", "ふじわらのなんけとよなり"],
  slug: null,
  category: "person",
},
"iratsume": {
  canonical: "郎女（死者の書）",
  aliases: ["郎女", "いらつめ"],
  slug: null,
  category: "person",
},
"taima-mandala": {
  canonical: "当麻曼荼羅",
  aliases: ["当麻曼荼羅"],
  slug: null,
  category: "work",
},
"taimadera": {
  canonical: "当麻寺",
  aliases: ["当麻寺"],
  slug: null,
  category: "work",
},
"yoshimoto-yu-as-bible": {
  canonical: "喩としての聖書──マルコ伝（吉本隆明）",
  aliases: ["喩としての聖書", "喩としての聖書──マルコ伝"],
  slug: null,
  category: "work",
},
"kobayashi-taema": {
  canonical: "当麻（小林秀雄）",
  aliases: ["当麻"],
  slug: null,
  category: "work",
},
"umewaka-manzaburo": {
  canonical: "梅若万三郎",
  aliases: ["梅若万三郎"],
  slug: null,
  category: "person",
},
"zeami": {
  canonical: "世阿弥",
  aliases: ["世阿弥"],
  slug: null,
  category: "person",
},
"kondo-yoko-shisha": {
  canonical: "死者の書（近藤よう子・漫画版）",
  aliases: ["死者の書"],
  slug: null,
  category: "work",
},
"kawamoto-shisha-film": {
  canonical: "死者の書（川本喜八郎・映画）",
  aliases: ["死者の書"],
  slug: null,
  category: "work",
},
"atavism": {
  canonical: "間欠遺伝",
  aliases: ["間欠遺伝", "アタヴィズム"],
  slug: null,
  category: "concept",
},
"yamagishi-ryoko": {
  canonical: "山岸凉子",
  aliases: ["山岸凉子"],
  slug: "0013",
  category: "person",
},
"hi-izuru-tokoro-no-tenshi": {
  canonical: "日出処の天子",
  aliases: ["日出処の天子"],
  slug: "0013",
  category: "work",
},
"shotoku-taishi": {
  canonical: "聖徳太子",
  aliases: ["聖徳太子", "厩戸皇子", "厩戸王"],
  slug: null,
  category: "person",
},
"yamagata-hiroo": {
  canonical: "山形浩生",
  aliases: ["山形浩生"],
  slug: null,
  category: "person",
},
"yamagata-shin-kyoyo": {
  canonical: "新教養主義宣言（山形浩生）",
  aliases: ["新教養主義宣言"],
  slug: null,
  category: "work",
},
"morohoshi-daijiro": {
  canonical: "諸星大二郎",
  aliases: ["諸星大二郎"],
  slug: null,
  category: "person",
},
"ankoku-shinwa": {
  canonical: "暗黒神話",
  aliases: ["暗黒神話"],
  slug: null,
  category: "work",
},
"koshi-ankokuden": {
  canonical: "孔子暗黒伝",
  aliases: ["孔子暗黒伝"],
  slug: null,
  category: "work",
},
"yokai-hunter": {
  canonical: "妖怪ハンター",
  aliases: ["妖怪ハンター"],
  slug: null,
  category: "work",
},
"umehara-takeshi": {
  canonical: "梅原猛",
  aliases: ["梅原猛"],
  slug: null,
  category: "person",
},
"kakusareta-juujika": {
  canonical: "隠された十字架 法隆寺論",
  aliases: ["隠された十字架", "隠された十字架 法隆寺論"],
  slug: null,
  category: "work",
},
"horyuji": {
  canonical: "法隆寺",
  aliases: ["法隆寺"],
  slug: null,
  category: "work",
},
"yumedono": {
  canonical: "夢殿",
  aliases: ["夢殿"],
  slug: null,
  category: "work",
},
"naoki-kojiro": {
  canonical: "直木孝次郎",
  aliases: ["直木孝次郎"],
  slug: null,
  category: "person",
},
"josephine-tey": {
  canonical: "ジョセフィン・テイ",
  aliases: ["ジョセフィン・テイ", "Josephine Tey"],
  slug: null,
  category: "person",
},
"daughter-of-time": {
  canonical: "時の娘",
  aliases: ["時の娘"],
  slug: null,
  category: "work",
},
"aramata-hiroshi": {
  canonical: "荒俣宏",
  aliases: ["荒俣宏"],
  slug: null,
  category: "person",
},
"nakajima-ramo": {
  canonical: "中島らも",
  aliases: ["中島らも"],
  slug: null,
  category: "person",
},
"murakami-haruki": {
  canonical: "村上春樹",
  aliases: ["村上春樹"],
  slug: null,
  category: "person",
},
"kawai-hayao": {
  canonical: "河合隼雄",
  aliases: ["河合隼雄"],
  slug: null,
  category: "person",
},
"murakami-kawai-book": {
  canonical: "村上春樹、河合隼雄に会いにいく",
  aliases: ["村上春樹、河合隼雄に会いにいく"],
  slug: null,
  category: "work",
},
"genji-monogatari": {
  canonical: "源氏物語",
  aliases: ["源氏物語"],
  slug: null,
  category: "work",
},
"fukazawa-shichiro": {
  canonical: "深沢七郎",
  aliases: ["深沢七郎"],
  slug: null,
  category: "person",
},
"narayama-bushiko": {
  canonical: "楢山節考",
  aliases: ["楢山節考"],
  slug: null,
  category: "work",
},
"masamune-hakucho": {
  canonical: "正宗白鳥",
  aliases: ["正宗白鳥"],
  slug: null,
  category: "person",
},
"tange-kenzo": {
  canonical: "丹下健三",
  aliases: ["丹下健三", "Kenzo Tange"],
  slug: "0014",
  category: "person",
},
"tokyo-plan-1960": {
  canonical: "東京計画1960",
  aliases: ["東京計画1960"],
  slug: "0014",
  category: "work",
},
"goto-shimpei": {
  canonical: "後藤新平",
  aliases: ["後藤新平"],
  slug: null,
  category: "person",
},
"ishikawa-hideaki": {
  canonical: "石川栄耀",
  aliases: ["石川栄耀"],
  slug: null,
  category: "person",
},
"kanto-earthquake": {
  canonical: "関東大震災",
  aliases: ["関東大震災"],
  slug: null,
  category: "concept",
},
"kano-hisaaki": {
  canonical: "加納久朗",
  aliases: ["加納久朗"],
  slug: null,
  category: "person",
},
"neo-tokyo-plan": {
  canonical: "ネオ・トウキョウ・プラン",
  aliases: ["ネオ・トウキョウ・プラン"],
  slug: null,
  category: "work",
},
"kikutake-kiyonori": {
  canonical: "菊竹清訓",
  aliases: ["菊竹清訓"],
  slug: null,
  category: "person",
},
"tower-city-kikutake": {
  canonical: "塔状都市（菊竹清訓）",
  aliases: ["塔状都市"],
  slug: null,
  category: "work",
},
"marine-city-kikutake": {
  canonical: "海上都市（菊竹清訓）",
  aliases: ["海上都市"],
  slug: null,
  category: "work",
},
"isozaki-arata": {
  canonical: "磯崎新",
  aliases: ["磯崎新"],
  slug: null,
  category: "person",
},
"city-in-the-air": {
  canonical: "空中都市（磯崎新）",
  aliases: ["空中都市"],
  slug: null,
  category: "work",
},
"metabolism-architecture": {
  canonical: "メタボリズム",
  aliases: ["メタボリズム", "新陳代謝"],
  slug: null,
  category: "concept",
},
"kurokawa-kisho": {
  canonical: "黒川紀章",
  aliases: ["黒川紀章"],
  slug: null,
  category: "person",
},
"nakagin-capsule-tower": {
  canonical: "中銀カプセルタワービル",
  aliases: ["中銀カプセルタワービル"],
  slug: null,
  category: "work",
},
"miyakonojo-civic-hall": {
  canonical: "都城市民会館",
  aliases: ["都城市民会館"],
  slug: null,
  category: "work",
},
"rainbow-bridge": {
  canonical: "レインボーブリッジ",
  aliases: ["レインボーブリッジ"],
  slug: null,
  category: "work",
},
"fuji-tv-building": {
  canonical: "フジテレビ本社ビル",
  aliases: ["フジテレビ本社ビル"],
  slug: null,
  category: "work",
},
"le-corbusier": {
  canonical: "ル・コルビュジエ",
  aliases: ["ル・コルビュジエ", "ル・コルビジエ", "Le Corbusier"],
  slug: "0015",
  category: "person",
},
"ville-contemporaine": {
  canonical: "300万人のための現代都市",
  aliases: ["300万人のための現代都市"],
  slug: null,
  category: "work",
},
"plan-voisin": {
  canonical: "ヴォワザン計画",
  aliases: ["ヴォワザン計画"],
  slug: null,
  category: "work",
},
"ville-radieuse": {
  canonical: "輝く都市",
  aliases: ["輝く都市"],
  slug: null,
  category: "work",
},
"akira-manga": {
  canonical: "AKIRA（大友克洋）",
  aliases: ["AKIRA"],
  slug: null,
  category: "work",
},
"otomo-katsuhiro": {
  canonical: "大友克洋",
  aliases: ["大友克洋"],
  slug: null,
  category: "person",
},
"ghost-in-the-shell": {
  canonical: "攻殻機動隊",
  aliases: ["攻殻機動隊"],
  slug: null,
  category: "work",
},
"evangelion": {
  canonical: "新世紀エヴァンゲリオン",
  aliases: ["新世紀エヴァンゲリオン", "エヴァンゲリオン"],
  slug: null,
  category: "work",
},
"tsukuba-syndrome": {
  canonical: "筑波病",
  aliases: ["筑波病", "つくばシンドローム"],
  slug: null,
  category: "concept",
},
"dodge-line": {
  canonical: "ドッジ・ライン",
  aliases: ["ドッジ・ライン"],
  slug: null,
  category: "concept",
},
"ronchamp-chapel": {
  canonical: "ロンシャンの礼拝堂",
  aliases: ["ロンシャンの礼拝堂", "ノートルダム・デュ・オー礼拝堂"],
  slug: "0015",
  category: "work",
},
"jean-arp": {
  canonical: "ジャン・アルプ",
  aliases: ["ジャン・アルプ", "ハンス・アルプ", "Jean Arp", "Hans Arp"],
  slug: null,
  category: "person",
},
"alexander-calder": {
  canonical: "アレクサンダー・カルダー",
  aliases: ["アレクサンダー・カルダー", "Alexander Calder"],
  slug: null,
  category: "person",
},
"wassily-kandinsky": {
  canonical: "ヴァシリー・カンディンスキー",
  aliases: ["カンディンスキー", "ヴァシリー・カンディンスキー", "Wassily Kandinsky"],
  slug: null,
  category: "person",
},
"joan-miro": {
  canonical: "ジョアン・ミロ",
  aliases: ["ミロ", "ジョアン・ミロ", "Joan Miró"],
  slug: null,
  category: "person",
},
"herbert-read": {
  canonical: "ハーバート・リード",
  aliases: ["ハーバート・リード", "Herbert Read"],
  slug: null,
  category: "person",
},
"henry-moore": {
  canonical: "ヘンリー・ムーア",
  aliases: ["ヘンリー・ムーア", "Henry Moore"],
  slug: null,
  category: "person",
},
"barbara-hepworth": {
  canonical: "バーバラ・ヘップワース",
  aliases: ["バーバラ・ヘップワース", "Barbara Hepworth"],
  slug: null,
  category: "person",
},
"alfred-barr": {
  canonical: "アルフレッド・バー",
  aliases: ["アルフレッド・バー", "Alfred H. Barr Jr."],
  slug: null,
  category: "person",
},
"cubism-and-abstract-art": {
  canonical: "キュビスムと抽象芸術（展覧会）",
  aliases: ["キュビスムと抽象芸術"],
  slug: null,
  category: "work",
},
"biomorphic-form": {
  canonical: "バイオモーフィック・フォルム",
  aliases: ["バイオモーフィック・フォルム", "biomorphic form", "生物形態"],
  slug: null,
  category: "concept",
},
"vitalism-art": {
  canonical: "バイタリズム（美術）",
  aliases: ["バイタリズム", "生命主義"],
  slug: null,
  category: "concept",
},
"piet-mondrian": {
  canonical: "ピート・モンドリアン",
  aliases: ["モンドリアン", "ピート・モンドリアン", "Piet Mondrian"],
  slug: null,
  category: "person",
},
"de-stijl": {
  canonical: "デ・ステイル",
  aliases: ["デ・ステイル", "De Stijl"],
  slug: null,
  category: "concept",
},
"gerrit-rietveld": {
  canonical: "ヘリット・リートフェルト",
  aliases: ["ヘリット・リートフェルト", "リートフェルト", "Gerrit Rietveld"],
  slug: null,
  category: "person",
},
"schroder-house": {
  canonical: "シュレーダー邸",
  aliases: ["シュレーダー邸"],
  slug: null,
  category: "work",
},
"domino-system": {
  canonical: "ドミノシステム",
  aliases: ["ドミノシステム"],
  slug: null,
  category: "concept",
},
"five-points-architecture": {
  canonical: "近代建築の五原則",
  aliases: ["近代建築の五原則", "近代建築の5原則"],
  slug: null,
  category: "concept",
},
"amedee-ozenfant": {
  canonical: "アメデ・オザンファン",
  aliases: ["アメデ・オザンファン", "オザンファン", "Amédée Ozenfant"],
  slug: null,
  category: "person",
},
"purism": {
  canonical: "ピュリスム",
  aliases: ["ピュリスム", "純粋主義", "Purism"],
  slug: null,
  category: "concept",
},
"fernand-leger": {
  canonical: "フェルナン・レジェ",
  aliases: ["フェルナン・レジェ", "Fernand Léger"],
  slug: null,
  category: "person",
},
"pablo-picasso": {
  canonical: "パブロ・ピカソ",
  aliases: ["ピカソ", "パブロ・ピカソ", "Pablo Picasso"],
  slug: null,
  category: "person",
},
"andre-breton": {
  canonical: "アンドレ・ブルトン",
  aliases: ["アンドレ・ブルトン", "André Breton"],
  slug: null,
  category: "person",
},
"takiguchi-shuzo": {
  canonical: "瀧口修造",
  aliases: ["瀧口修造"],
  slug: null,
  category: "person",
},
"modulor": {
  canonical: "モデュロール",
  aliases: ["モデュロール", "Modulor"],
  slug: null,
  category: "concept",
},
"antonio-gaudi": {
  canonical: "アントニオ・ガウディ",
  aliases: ["ガウディ", "アントニオ・ガウディ", "Antoni Gaudí"],
  slug: null,
  category: "person",
},
"ando-tadao": {
  canonical: "安藤忠雄",
  aliases: ["安藤忠雄"],
  slug: null,
  category: "person",
},
"church-of-light": {
  canonical: "光の教会",
  aliases: ["光の教会"],
  slug: null,
  category: "work",
},
"tokyo-cathedral": {
  canonical: "東京カテドラル聖マリア大聖堂",
  aliases: ["東京カテドラル聖マリア大聖堂", "東京カテドラル"],
  slug: null,
  category: "work",
},
"iwaaki-hitoshi": {
  canonical: "岩明均",
  aliases: ["岩明均"],
  slug: null,
  category: "person",
},
"parasyte": {
  canonical: "寄生獣",
  aliases: ["寄生獣"],
  slug: null,
  category: "work",
},
"objets-reaction-poetique": {
  canonical: "詩的反応を喚起するもの",
  aliases: ["詩的反応を喚起するもの", "Objets à réaction poétique"],
  slug: null,
  category: "concept",
},
"acoustique-visuelle": {
  canonical: "視覚的な音響",
  aliases: ["視覚的な音響", "acoustique visuelle"],
  slug: null,
  category: "concept",
},
"jacques-tati": {
  canonical: "ジャック・タチ",
  aliases: ["ジャック・タチ", "Jacques Tati"],
  slug: "0016",
  category: "person",
},
"playtime": {
  canonical: "プレイタイム",
  aliases: ["プレイタイム", "Playtime"],
  slug: "0016",
  category: "work",
},
"tativille": {
  canonical: "タチヴィル",
  aliases: ["タチヴィル", "Tativille"],
  slug: null,
  category: "work",
},
"mon-oncle": {
  canonical: "ぼくの伯父さん",
  aliases: ["ぼくの伯父さん", "Mon Oncle"],
  slug: null,
  category: "work",
},
"monsieur-hulot": {
  canonical: "ユロ氏",
  aliases: ["ユロ氏", "Monsieur Hulot"],
  slug: null,
  category: "person",
},
"francois-truffaut": {
  canonical: "フランソワ・トリュフォー",
  aliases: ["フランソワ・トリュフォー", "François Truffaut"],
  slug: null,
  category: "person",
},
"orson-welles": {
  canonical: "オーソン・ウェルズ",
  aliases: ["オーソン・ウェルズ", "Orson Welles"],
  slug: null,
  category: "person",
},
"jean-luc-godard": {
  canonical: "ジャン＝リュック・ゴダール",
  aliases: ["ゴダール", "ジャン＝リュック・ゴダール", "Jean-Luc Godard"],
  slug: null,
  category: "person",
},
"weekend-godard": {
  canonical: "ウイークエンド（ゴダール）",
  aliases: ["ウイークエンド", "Week End"],
  slug: null,
  category: "work",
},
"loin-du-vietnam": {
  canonical: "ベトナムから遠く離れて",
  aliases: ["ベトナムから遠く離れて", "Loin du Vietnam"],
  slug: null,
  category: "work",
},
"chris-marker": {
  canonical: "クリス・マルケル",
  aliases: ["クリス・マルケル", "Chris Marker"],
  slug: null,
  category: "person",
},
"alain-resnais": {
  canonical: "アラン・レネ",
  aliases: ["アラン・レネ", "Alain Resnais"],
  slug: null,
  category: "person",
},
"agnes-varda": {
  canonical: "アニエス・ヴァルダ",
  aliases: ["アニエス・ヴァルダ", "Agnès Varda"],
  slug: null,
  category: "person",
},
"claude-lelouch": {
  canonical: "クロード・ルルーシュ",
  aliases: ["クロード・ルルーシュ", "Claude Lelouch"],
  slug: null,
  category: "person",
},
"joris-ivens": {
  canonical: "ヨリス・イヴェンス",
  aliases: ["ヨリス・イヴェンス", "Joris Ivens"],
  slug: null,
  category: "person",
},
"william-klein": {
  canonical: "ウィリアム・クライン",
  aliases: ["ウィリアム・クライン", "William Klein"],
  slug: null,
  category: "person",
},
"may-1968": {
  canonical: "五月革命",
  aliases: ["五月革命", "Mai 68"],
  slug: null,
  category: "concept",
},
} as const;